spring:
  application:
    name: uni-master-monolith-som
  data:
    rest:
      basePath: /api
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8081